### ISSUE TITLE
Set variable to random number returns null. (Missing curly braces)

### ISSUE THREAD

**Issue by BrandonMakin** [dialogic-godot/dialogic#2093] opened 2024-02-17 00:19 UTC
## The problem

**Describe the bug**
When using the timeline visual editor set a variable to a random number, null is returned instead of a number. This seems to be a regression in Alpha 13.
The text representation of this line reveals the issue: `range(a,b).pick_random()` is not surrounded by braces.

**To Reproduce**
1. Open a timeline in the timeline visual editor
2. Click on "Set Variable". On the left-hand side of the equation, choose any variable. On the right-hand side, choose "Random Number".
3. (Optional) Go to the text editor. You will see something like: `set {foo} = range(0,100).pick_random()`. 
4. Play the timeline. The right-hand expression will resolve to null, and you will get this error upon attempting to assign null:
```
Dialogic: Expression failed to execute: Invalid named index 'foo' for base type Object
[Dialogic] Failed parsing variable/expression 'foo'.
```

**Expected behavior**
The text representation should include curly braces like so: `set {foo} = {range(0,100).pick_random()}`
When the timeline plays, the variable should be assigned correctly.

**System (please complete the following information):**
 - OS: Windows 11
 - Godot Version: v4.2.1.stable.mono.official [b09f793f5]
 - Dialogic Version: 2.0 Alpha 13

## Solutions
**Possible fixes**
Add braces around the right-hand side of random expressions: `set {foo} = {range(0,100).pick_random()}`.  Note that there may be other places with a similar issue in the code base.

**Comment by BrandonMakin** [comment] 2024-02-17 00:23
Relatedly, the errors I received could be more helpful if Dialogic automatically checks for attempts to pass null. Perhaps more broadly, Dialogic should always type check calls to `Set`. Either way it seems to me that Dialogic should always at least warn the user when null is being passed to a variable. I don't know if I should create a separate issue to address this.

**Comment by BrandonMakin** [comment] 2024-02-17 00:25
Setting a variable to any expression in the visual editor also doesn't add curly braces. I suspect that this is unintentional.

**Comment by BrandonMakin** [comment] 2024-02-17 00:31
Adding curly brackets to `set` in the text editor as I described works correctly. However, the visual editor then shows the expression as a variable, as seen here: 
![image](https://github.com/dialogic-godot/dialogic/assets/7276621/0bc97b19-094f-4cc8-b6b3-8df1be296f15)
(Text version: `set {riddles.next_question} = {range(0,8).pick_random()}`)

Should random numbers and other expressions be surrounded by curly braces? If not, that should be fixed. If so, then the visual editor needs to be updated.

**Comment by Jowan-Spooner** [comment] 2024-02-17 09:57
I actually do believe this has been fixed on main. While adding curly braces does work here, the  right side of the expression should be considered an expression without it already.

Maybe you could try this with the latest version on main?

**Comment by Jowan-Spooner** [comment] 2024-02-19 15:57
@BrandonMakin Could you try this again with the version on main?

**Comment by Jowan-Spooner** [comment] 2024-02-22 08:45
I will close this as I cannot reproduce it on main.

**Closed by Jowan-Spooner** 2024-02-22 08:45 UTC
Labels: Bug 🐞
