### ISSUE TITLE
Timeline crashes in between condition and choice on End Branch event

### ISSUE THREAD

**Issue by Tetragramat** [dialogic-godot/dialogic#2375] opened 2024-08-22 21:23 UTC
## The problem

**Describe the bug**
When I run timeline with specific event sequence. The timeline crashes with `Invalid access to property or key 'current_event_idx' on a base object of type 'Nil'.`

**To Reproduce**
1. create timeline 
```
if false:
- choice
```
2. click on "Play timeline"

**Expected behavior**
Timeline runs and ends without error.

**Screenshots**
![errrr](https://github.com/user-attachments/assets/4e6b316a-d2fd-4fda-9e56-4596bf7d72d7)

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 4.3
 - Dialogic Version: 2.0 Alpha 14

## Solutions

**Workaround**

Add comment after condition where timeline crashes
```
if false:
# comment or text event
- choice
```

**Possible fixes**

No idea.

**Comment by firedfromlife** [comment] 2024-08-23 06:30
@Jowan-Spooner @Tetragramat 
I was unable to reproduce this bug in the current main branch of Dialogic on Godot 4.3.

**Comment by Tetragramat** [comment] 2024-08-23 21:49
New project on Godot 4.3 with fresh download of Dialogic from https://github.com/dialogic-godot/dialogic/archive/refs/tags/2.0-alpha-14.zip


Reproduction:

https://github.com/user-attachments/assets/4bf3e70c-8f01-47b9-9a0d-7a7ddfb6600f

**Comment by Jowan-Spooner** [comment] 2024-08-25 09:38
I think this should be fixed on main now. Feel free to test the main branch and let me know!

**Closed** 2024-08-30 16:03 UTC
Labels: Bug 🐞, Planned

**Comment by Mendoxes** [comment] 2024-09-19 19:48
Hello i have a similar problem:
![image](https://github.com/user-attachments/assets/f239dbe2-7fc2-4fdd-ad98-3c4cc865ff58)
it crashes when i just enter a simple if with choice under it
